// <auto-generated />
using System;
using GuildRosterMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildRosterMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220413132410_fixSpecialization")]
    partial class fixSpecialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GuildRosterModels.GuildRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GuildRankName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("GuildRanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuildRankName = "Guild Master"
                        },
                        new
                        {
                            Id = 2,
                            GuildRankName = "Officer"
                        },
                        new
                        {
                            Id = 3,
                            GuildRankName = "Member"
                        },
                        new
                        {
                            Id = 4,
                            GuildRankName = "Trial"
                        });
                });

            modelBuilder.Entity("GuildRosterModels.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GuildRankId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("WowClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildRankId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WowClassId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GuildRosterModels.PlayerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Tank"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Healer"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Melee DPS"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Ranged DPS"
                        });
                });

            modelBuilder.Entity("GuildRosterModels.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WowClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("WowClassId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            SpecName = "Blood",
                            WowClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 3,
                            SpecName = "Frost",
                            WowClassId = 1
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 3,
                            SpecName = "Blood",
                            WowClassId = 1
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 1,
                            SpecName = "Vengeance",
                            WowClassId = 2
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 3,
                            SpecName = "Havoc",
                            WowClassId = 2
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 1,
                            SpecName = "Guardian",
                            WowClassId = 3
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 2,
                            SpecName = "Restoration",
                            WowClassId = 3
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 3,
                            SpecName = "Feral",
                            WowClassId = 3
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 4,
                            SpecName = "Balance",
                            WowClassId = 3
                        },
                        new
                        {
                            Id = 10,
                            RoleId = 3,
                            SpecName = "Survival",
                            WowClassId = 4
                        },
                        new
                        {
                            Id = 11,
                            RoleId = 4,
                            SpecName = "Beast Mastery",
                            WowClassId = 4
                        },
                        new
                        {
                            Id = 12,
                            RoleId = 4,
                            SpecName = "Marksmanship",
                            WowClassId = 4
                        },
                        new
                        {
                            Id = 13,
                            RoleId = 4,
                            SpecName = "Fire",
                            WowClassId = 5
                        },
                        new
                        {
                            Id = 14,
                            RoleId = 4,
                            SpecName = "Frost",
                            WowClassId = 5
                        },
                        new
                        {
                            Id = 15,
                            RoleId = 4,
                            SpecName = "Arcane",
                            WowClassId = 5
                        },
                        new
                        {
                            Id = 16,
                            RoleId = 1,
                            SpecName = "Brewmaster",
                            WowClassId = 6
                        },
                        new
                        {
                            Id = 17,
                            RoleId = 2,
                            SpecName = "Mistweaver",
                            WowClassId = 6
                        },
                        new
                        {
                            Id = 18,
                            RoleId = 3,
                            SpecName = "Windwalker",
                            WowClassId = 6
                        },
                        new
                        {
                            Id = 19,
                            RoleId = 1,
                            SpecName = "Protection",
                            WowClassId = 7
                        },
                        new
                        {
                            Id = 20,
                            RoleId = 2,
                            SpecName = "Holy",
                            WowClassId = 7
                        },
                        new
                        {
                            Id = 21,
                            RoleId = 3,
                            SpecName = "Retribution",
                            WowClassId = 7
                        },
                        new
                        {
                            Id = 22,
                            RoleId = 2,
                            SpecName = "Discipline",
                            WowClassId = 8
                        },
                        new
                        {
                            Id = 23,
                            RoleId = 2,
                            SpecName = "Holy",
                            WowClassId = 8
                        },
                        new
                        {
                            Id = 24,
                            RoleId = 4,
                            SpecName = "Shadow",
                            WowClassId = 8
                        },
                        new
                        {
                            Id = 25,
                            RoleId = 3,
                            SpecName = "Outlaw",
                            WowClassId = 9
                        },
                        new
                        {
                            Id = 26,
                            RoleId = 3,
                            SpecName = "Subtlety",
                            WowClassId = 9
                        },
                        new
                        {
                            Id = 27,
                            RoleId = 3,
                            SpecName = "Assassination",
                            WowClassId = 9
                        },
                        new
                        {
                            Id = 28,
                            RoleId = 2,
                            SpecName = "Restoration",
                            WowClassId = 10
                        },
                        new
                        {
                            Id = 29,
                            RoleId = 3,
                            SpecName = "Enhancement",
                            WowClassId = 10
                        },
                        new
                        {
                            Id = 30,
                            RoleId = 4,
                            SpecName = "Elemental",
                            WowClassId = 10
                        },
                        new
                        {
                            Id = 31,
                            RoleId = 4,
                            SpecName = "Destruction",
                            WowClassId = 11
                        },
                        new
                        {
                            Id = 32,
                            RoleId = 4,
                            SpecName = "Demonology",
                            WowClassId = 11
                        },
                        new
                        {
                            Id = 33,
                            RoleId = 4,
                            SpecName = "Affliction",
                            WowClassId = 11
                        },
                        new
                        {
                            Id = 34,
                            RoleId = 1,
                            SpecName = "Protection",
                            WowClassId = 12
                        },
                        new
                        {
                            Id = 35,
                            RoleId = 3,
                            SpecName = "Fury",
                            WowClassId = 12
                        },
                        new
                        {
                            Id = 36,
                            RoleId = 3,
                            SpecName = "Arms",
                            WowClassId = 12
                        });
                });

            modelBuilder.Entity("GuildRosterModels.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamName = "AOTC"
                        },
                        new
                        {
                            Id = 2,
                            TeamName = "Mythic Raiding"
                        },
                        new
                        {
                            Id = 3,
                            TeamName = "M+ Team 1"
                        });
                });

            modelBuilder.Entity("GuildRosterModels.WowClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("WowClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "Death Knight"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "Demon Hunter"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "Druid"
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "Hunter"
                        },
                        new
                        {
                            Id = 5,
                            ClassName = "Mage"
                        },
                        new
                        {
                            Id = 6,
                            ClassName = "Monk"
                        },
                        new
                        {
                            Id = 7,
                            ClassName = "Paladin"
                        },
                        new
                        {
                            Id = 8,
                            ClassName = "Priest"
                        },
                        new
                        {
                            Id = 9,
                            ClassName = "Rogue"
                        },
                        new
                        {
                            Id = 10,
                            ClassName = "Shaman"
                        },
                        new
                        {
                            Id = 11,
                            ClassName = "Warlock"
                        },
                        new
                        {
                            Id = 12,
                            ClassName = "Warrior"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GuildRosterModels.Player", b =>
                {
                    b.HasOne("GuildRosterModels.GuildRank", "GuildRank")
                        .WithMany("Players")
                        .HasForeignKey("GuildRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildRosterModels.PlayerRole", "Role")
                        .WithMany("Players")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildRosterModels.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("GuildRosterModels.WowClass", "WowClass")
                        .WithMany("Player")
                        .HasForeignKey("WowClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildRank");

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("WowClass");
                });

            modelBuilder.Entity("GuildRosterModels.Specialization", b =>
                {
                    b.HasOne("GuildRosterModels.PlayerRole", "Role")
                        .WithMany("Specs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildRosterModels.WowClass", "WowClass")
                        .WithMany("Spec")
                        .HasForeignKey("WowClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("WowClass");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildRosterModels.GuildRank", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("GuildRosterModels.PlayerRole", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Specs");
                });

            modelBuilder.Entity("GuildRosterModels.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("GuildRosterModels.WowClass", b =>
                {
                    b.Navigation("Player");

                    b.Navigation("Spec");
                });
#pragma warning restore 612, 618
        }
    }
}
